---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1677703/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp mekanisme.html $DEPLOYPATH
    - /bin/cp tentang.html $DEPLOYPATH
    - /bin/cp timeline.html $DEPLOYPATH
    - /bin/cp dataset.html $DEPLOYPATH
    - /bin/cp tim1.html $DEPLOYPATH
    - /bin/cp tim2.html $DEPLOYPATH
    - /bin/cp tim3.html $DEPLOYPATH
    - /bin/cp tim4.html $DEPLOYPATH
    - /bin/cp tim5.html $DEPLOYPATH
    - /bin/cp tim6.html $DEPLOYPATH
    - /bin/cp tim7.html $DEPLOYPATH
    - /bin/cp tim8.html $DEPLOYPATH
    - /bin/cp faq.html $DEPLOYPATH
    - /bin/cp top5.html $DEPLOYPATH
    - /bin/cp presentasi5tim.html $DEPLOYPATH
    - /bin/cp indexold.html $DEPLOYPATH
    - /bin/cp vanilla-tilt.min.js $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R paper $DEPLOYPATH
    - /bin/cp -R sertifikat $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
